name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '56 4 * * *'

jobs:
  build-php:
    name: PHP ${{ matrix.php-version }} with Composer ${{ matrix.composer-version }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        composer-version:
          - "v1"
          - "v2"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP version and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:${{ matrix.composer-version }}

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Require Composer@v1
        if: ${{ matrix.composer-version == 'v1' }}
        run: composer require "composer/composer:^1.10" --dev --no-update

      - name: Require Composer@v2
        if: ${{ matrix.composer-version == 'v2' }}
        run: composer require "composer/composer:^2.0" --dev --no-update

      - name: Install composer dependencies
        if: ${{ matrix.php-version <= '8.1' }}
        run: composer install

      - name: Install composer dependencies PHP 8.2
        # @todo: Needed until prophecy (req by phpunit) allows PHP 8.2, https://github.com/phpspec/prophecy/issues/556
        if: ${{ matrix.php-version > '8.1' }}
        run: composer install --ignore-platform-req=php+

      - name: Info
        run: composer info

      - name: Lint
        run: composer ci:php:lint

      # as long as PHP7.2 is supported, we cannot use a newer php-cs-fixer version which is compatible with PHP8.1+,
      # thus we have to limit cgl run down to lower than PHP8.1.
      # @todo remove version check after min PHP version has been raised to >= PHP7.4
      - name: CGL
        if: ${{ matrix.php-version < '8.1' }}
        run: composer cgl:check

      - name: UnitTests
        run: composer ci:php:tests:unit